worker_processes auto;

env JWT_SECRET;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    include conf.d/*.conf;
}